import type { RouteRecordRaw } from 'vue-router'

const educationRoutes: RouteRecordRaw[] = [
  {
    path: '/education',
    name: 'EducationRoot',
    redirect: '/education/foundation/tenants',
    meta: {
      title: '教务 SaaS',
      icon: 'material-symbols:school-outline-rounded',
      type: 'M',
      auth: ['education:*'],
    },
    children: [
      {
        path: '/education/foundation',
        name: 'EducationFoundation',
        redirect: '/education/foundation/tenants',
        meta: {
          title: '基础设置',
          icon: 'material-symbols:settings-outline-rounded',
          type: 'M',
          auth: ['education:foundation:tenant:page', 'education:foundation:campus:page', 'education:foundation:user-profile:page', 'education:foundation:dictionary:page', 'education:foundation:feature-flag:page', 'education:foundation:audit-log:page'],
        },
        children: [
          {
            path: '/education/foundation/tenants',
            name: 'EducationFoundationTenantList',
            component: () => import('~/education/views/foundation/TenantList.vue'),
            meta: {
              title: '机构',
              icon: 'material-symbols:business-center-outline-rounded',
              type: 'M',
              auth: ['education:foundation:tenant:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/campuses',
            name: 'EducationFoundationCampusList',
            component: () => import('~/education/views/foundation/CampusList.vue'),
            meta: {
              title: '校区',
              icon: 'material-symbols:location-city-outline-rounded',
              type: 'M',
              auth: ['education:foundation:campus:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/user-profiles',
            name: 'EducationFoundationUserProfileList',
            component: () => import('~/education/views/foundation/UserProfileList.vue'),
            meta: {
              title: '人员权限',
              icon: 'material-symbols:manage-accounts-outline-rounded',
              type: 'M',
              auth: ['education:foundation:user-profile:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/dictionaries',
            name: 'EducationFoundationDictionaryList',
            component: () => import('~/education/views/foundation/DictionaryList.vue'),
            meta: {
              title: '字典配置',
              icon: 'material-symbols:format-list-bulleted-rounded',
              type: 'M',
              auth: ['education:foundation:dictionary:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/feature-flags',
            name: 'EducationFoundationFeatureFlagList',
            component: () => import('~/education/views/foundation/FeatureFlagList.vue'),
            meta: {
              title: '功能开关',
              icon: 'material-symbols:toggle-on-outline-rounded',
              type: 'M',
              auth: ['education:foundation:feature-flag:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/audit-logs',
            name: 'EducationFoundationAuditLogList',
            component: () => import('~/education/views/foundation/AuditLogList.vue'),
            meta: {
              title: 'Audit Logs',
              icon: 'i-lucide-file-clock',
              type: 'M',
              auth: ['education:foundation:audit-log:page'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/academic',
        name: 'EducationAcademic',
        redirect: '/education/academic/dashboard',
        meta: {
          title: 'V1 Academic',
          icon: 'material-symbols:auto-stories-outline-rounded',
          type: 'M',
          auth: ['education:academic:report:dashboard', 'education:academic:report:attendance', 'education:academic:report:consumption', 'education:academic:report:account-balance', 'education:academic:report:leave', 'education:academic:report:acceptance', 'education:academic:classroom:page', 'education:academic:student:page', 'education:academic:guardian:page', 'education:academic:teacher:page', 'education:academic:course:page', 'education:academic:lesson-package:page', 'education:academic:enrollment:page', 'education:academic:student-course-account:page', 'education:academic:class:page', 'education:academic:lesson-schedule:calendar', 'education:academic:lesson:page', 'education:academic:attendance:lesson-page', 'education:academic:leave-request:page', 'education:academic:lesson-change:page', 'education:academic:consumption:page', 'education:academic:account-adjustment:page', 'education:academic:notice:page'],
        },
        children: [
          {
            path: '/education/academic/dashboard',
            name: 'EducationAcademicDashboard',
            component: () => import('~/education/views/academic/AcademicDashboard.vue'),
            meta: {
              title: 'Academic Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:dashboard'],
              cache: true,
            },
          },
          {
            path: '/education/academic/classrooms',
            name: 'EducationAcademicClassroomList',
            component: () => import('~/education/views/academic/ClassroomList.vue'),
            meta: {
              title: 'Classrooms',
              icon: 'material-symbols:meeting-room-outline-rounded',
              type: 'M',
              auth: ['education:academic:classroom:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/students',
            name: 'EducationAcademicStudentList',
            component: () => import('~/education/views/academic/StudentList.vue'),
            meta: {
              title: 'Students',
              icon: 'material-symbols:face-3-outline-rounded',
              type: 'M',
              auth: ['education:academic:student:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/guardians',
            name: 'EducationAcademicGuardianList',
            component: () => import('~/education/views/academic/GuardianList.vue'),
            meta: {
              title: 'Guardians',
              icon: 'material-symbols:family-restroom-rounded',
              type: 'M',
              auth: ['education:academic:guardian:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/teachers',
            name: 'EducationAcademicTeacherList',
            component: () => import('~/education/views/academic/TeacherList.vue'),
            meta: {
              title: 'Teachers',
              icon: 'material-symbols:co-present-outline-rounded',
              type: 'M',
              auth: ['education:academic:teacher:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/courses',
            name: 'EducationAcademicCourseList',
            component: () => import('~/education/views/academic/CourseList.vue'),
            meta: {
              title: 'Courses',
              icon: 'material-symbols:menu-book-outline-rounded',
              type: 'M',
              auth: ['education:academic:course:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lesson-packages',
            name: 'EducationAcademicLessonPackageList',
            component: () => import('~/education/views/academic/LessonPackageList.vue'),
            meta: {
              title: 'Lesson Packages',
              icon: 'material-symbols:inventory-2-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson-package:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/enrollments',
            name: 'EducationAcademicEnrollmentWorkbench',
            component: () => import('~/education/views/academic/EnrollmentWorkbench.vue'),
            meta: {
              title: 'Enrollments',
              icon: 'material-symbols:how-to-reg-outline-rounded',
              type: 'M',
              auth: ['education:academic:enrollment:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/course-accounts',
            name: 'EducationAcademicAccountLedgerList',
            component: () => import('~/education/views/academic/AccountLedgerList.vue'),
            meta: {
              title: 'Course Accounts',
              icon: 'material-symbols:account-balance-wallet-outline-rounded',
              type: 'M',
              auth: ['education:academic:student-course-account:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/classes',
            name: 'EducationAcademicClassList',
            component: () => import('~/education/views/academic/ClassList.vue'),
            meta: {
              title: 'Classes',
              icon: 'material-symbols:groups-outline-rounded',
              type: 'M',
              auth: ['education:academic:class:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lesson-schedule',
            name: 'EducationAcademicLessonScheduleCalendar',
            component: () => import('~/education/views/academic/LessonScheduleCalendar.vue'),
            meta: {
              title: 'Lesson Schedule',
              icon: 'material-symbols:calendar-month-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson-schedule:calendar'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lessons',
            name: 'EducationAcademicLessonList',
            component: () => import('~/education/views/academic/LessonList.vue'),
            meta: {
              title: 'Lessons',
              icon: 'material-symbols:event-note-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/attendance-review',
            name: 'EducationAcademicAttendanceReview',
            component: () => import('~/education/views/academic/AttendanceReview.vue'),
            meta: {
              title: 'Attendance Review',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:academic:attendance:lesson-page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/leave-requests',
            name: 'EducationAcademicLeaveRequestList',
            component: () => import('~/education/views/academic/LeaveRequestList.vue'),
            meta: {
              title: 'Leave Requests',
              icon: 'material-symbols:event-busy-outline-rounded',
              type: 'M',
              auth: ['education:academic:leave-request:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lesson-changes',
            name: 'EducationAcademicLessonChangeList',
            component: () => import('~/education/views/academic/LessonChangeList.vue'),
            meta: {
              title: 'Lesson Changes',
              icon: 'material-symbols:move-up-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson-change:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/consumptions',
            name: 'EducationAcademicConsumptionLedgerList',
            component: () => import('~/education/views/academic/ConsumptionLedgerList.vue'),
            meta: {
              title: 'Consumption Ledger',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:academic:consumption:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/account-adjustments',
            name: 'EducationAcademicAccountAdjustmentList',
            component: () => import('~/education/views/academic/AccountAdjustmentList.vue'),
            meta: {
              title: 'Account Adjustments',
              icon: 'material-symbols:price-change-outline-rounded',
              type: 'M',
              auth: ['education:academic:account-adjustment:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/notices',
            name: 'EducationAcademicNoticeList',
            component: () => import('~/education/views/academic/NoticeList.vue'),
            meta: {
              title: 'Notices',
              icon: 'material-symbols:campaign-outline-rounded',
              type: 'M',
              auth: ['education:academic:notice:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/attendance',
            name: 'EducationAttendanceReport',
            component: () => import('~/education/views/academic/AttendanceReport.vue'),
            meta: {
              title: 'Attendance Report',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:attendance'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/consumption',
            name: 'EducationConsumptionReport',
            component: () => import('~/education/views/academic/ConsumptionReport.vue'),
            meta: {
              title: 'Consumption Report',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:consumption'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/account-balances',
            name: 'EducationAccountBalanceReport',
            component: () => import('~/education/views/academic/AccountBalanceReport.vue'),
            meta: {
              title: 'Account Balance Report',
              icon: 'material-symbols:account-balance-wallet-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:account-balance'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/leaves',
            name: 'EducationLeaveReport',
            component: () => import('~/education/views/academic/LeaveReport.vue'),
            meta: {
              title: 'Leave Report',
              icon: 'material-symbols:event-busy-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:leave'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/v1-acceptance',
            name: 'EducationV1AcceptanceReport',
            component: () => import('~/education/views/academic/V1AcceptanceReport.vue'),
            meta: {
              title: 'V1 Acceptance',
              icon: 'material-symbols:verified-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:acceptance'],
              cache: true,
            },
          },
        ],
      },
    ],
  },
]

export default educationRoutes
