import type { RouteRecordRaw } from 'vue-router'

const educationRoutes: RouteRecordRaw[] = [
  {
    path: '/education',
    name: 'EducationRoot',
    redirect: '/education/foundation/tenants',
    meta: {
      title: '教务 SaaS',
      icon: 'material-symbols:school-outline-rounded',
      type: 'M',
      auth: ['education:*'],
    },
    children: [
      {
        path: '/education/foundation',
        name: 'EducationFoundation',
        redirect: '/education/foundation/tenants',
        meta: {
          title: '基础设置',
          icon: 'material-symbols:settings-outline-rounded',
          type: 'M',
          auth: ['education:foundation:tenant:page', 'education:foundation:campus:page', 'education:foundation:user-profile:page', 'education:foundation:dictionary:page', 'education:foundation:feature-flag:page', 'education:foundation:audit-log:page'],
        },
        children: [
          {
            path: '/education/foundation/tenants',
            name: 'EducationFoundationTenantList',
            component: () => import('~/education/views/foundation/TenantList.vue'),
            meta: {
              title: '机构',
              icon: 'material-symbols:business-center-outline-rounded',
              type: 'M',
              auth: ['education:foundation:tenant:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/campuses',
            name: 'EducationFoundationCampusList',
            component: () => import('~/education/views/foundation/CampusList.vue'),
            meta: {
              title: '校区',
              icon: 'material-symbols:location-city-outline-rounded',
              type: 'M',
              auth: ['education:foundation:campus:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/user-profiles',
            name: 'EducationFoundationUserProfileList',
            component: () => import('~/education/views/foundation/UserProfileList.vue'),
            meta: {
              title: '人员权限',
              icon: 'material-symbols:manage-accounts-outline-rounded',
              type: 'M',
              auth: ['education:foundation:user-profile:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/dictionaries',
            name: 'EducationFoundationDictionaryList',
            component: () => import('~/education/views/foundation/DictionaryList.vue'),
            meta: {
              title: '字典配置',
              icon: 'material-symbols:format-list-bulleted-rounded',
              type: 'M',
              auth: ['education:foundation:dictionary:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/feature-flags',
            name: 'EducationFoundationFeatureFlagList',
            component: () => import('~/education/views/foundation/FeatureFlagList.vue'),
            meta: {
              title: '功能开关',
              icon: 'material-symbols:toggle-on-outline-rounded',
              type: 'M',
              auth: ['education:foundation:feature-flag:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/audit-logs',
            name: 'EducationFoundationAuditLogList',
            component: () => import('~/education/views/foundation/AuditLogList.vue'),
            meta: {
              title: 'Audit Logs',
              icon: 'i-lucide-file-clock',
              type: 'M',
              auth: ['education:foundation:audit-log:page'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/academic',
        name: 'EducationAcademic',
        redirect: '/education/academic/dashboard',
        meta: {
          title: 'V1 Academic',
          icon: 'material-symbols:auto-stories-outline-rounded',
          type: 'M',
          auth: ['education:academic:report:dashboard', 'education:academic:report:attendance', 'education:academic:report:consumption', 'education:academic:report:account-balance', 'education:academic:report:leave', 'education:academic:report:acceptance', 'education:academic:classroom:page', 'education:academic:student:page', 'education:academic:guardian:page', 'education:academic:teacher:page', 'education:academic:course:page', 'education:academic:lesson-package:page', 'education:academic:enrollment:page', 'education:academic:student-course-account:page', 'education:academic:class:page', 'education:academic:lesson-schedule:calendar', 'education:academic:lesson:page', 'education:academic:attendance:lesson-page', 'education:academic:leave-request:page', 'education:academic:lesson-change:page', 'education:academic:consumption:page', 'education:academic:account-adjustment:page', 'education:academic:notice:page'],
        },
        children: [
          {
            path: '/education/academic/dashboard',
            name: 'EducationAcademicDashboard',
            component: () => import('~/education/views/academic/AcademicDashboard.vue'),
            meta: {
              title: 'Academic Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:dashboard'],
              cache: true,
            },
          },
          {
            path: '/education/academic/classrooms',
            name: 'EducationAcademicClassroomList',
            component: () => import('~/education/views/academic/ClassroomList.vue'),
            meta: {
              title: 'Classrooms',
              icon: 'material-symbols:meeting-room-outline-rounded',
              type: 'M',
              auth: ['education:academic:classroom:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/students',
            name: 'EducationAcademicStudentList',
            component: () => import('~/education/views/academic/StudentList.vue'),
            meta: {
              title: 'Students',
              icon: 'material-symbols:face-3-outline-rounded',
              type: 'M',
              auth: ['education:academic:student:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/guardians',
            name: 'EducationAcademicGuardianList',
            component: () => import('~/education/views/academic/GuardianList.vue'),
            meta: {
              title: 'Guardians',
              icon: 'material-symbols:family-restroom-rounded',
              type: 'M',
              auth: ['education:academic:guardian:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/teachers',
            name: 'EducationAcademicTeacherList',
            component: () => import('~/education/views/academic/TeacherList.vue'),
            meta: {
              title: 'Teachers',
              icon: 'material-symbols:co-present-outline-rounded',
              type: 'M',
              auth: ['education:academic:teacher:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/courses',
            name: 'EducationAcademicCourseList',
            component: () => import('~/education/views/academic/CourseList.vue'),
            meta: {
              title: 'Courses',
              icon: 'material-symbols:menu-book-outline-rounded',
              type: 'M',
              auth: ['education:academic:course:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lesson-packages',
            name: 'EducationAcademicLessonPackageList',
            component: () => import('~/education/views/academic/LessonPackageList.vue'),
            meta: {
              title: 'Lesson Packages',
              icon: 'material-symbols:inventory-2-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson-package:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/enrollments',
            name: 'EducationAcademicEnrollmentWorkbench',
            component: () => import('~/education/views/academic/EnrollmentWorkbench.vue'),
            meta: {
              title: 'Enrollments',
              icon: 'material-symbols:how-to-reg-outline-rounded',
              type: 'M',
              auth: ['education:academic:enrollment:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/course-accounts',
            name: 'EducationAcademicAccountLedgerList',
            component: () => import('~/education/views/academic/AccountLedgerList.vue'),
            meta: {
              title: 'Course Accounts',
              icon: 'material-symbols:account-balance-wallet-outline-rounded',
              type: 'M',
              auth: ['education:academic:student-course-account:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/classes',
            name: 'EducationAcademicClassList',
            component: () => import('~/education/views/academic/ClassList.vue'),
            meta: {
              title: 'Classes',
              icon: 'material-symbols:groups-outline-rounded',
              type: 'M',
              auth: ['education:academic:class:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lesson-schedule',
            name: 'EducationAcademicLessonScheduleCalendar',
            component: () => import('~/education/views/academic/LessonScheduleCalendar.vue'),
            meta: {
              title: 'Lesson Schedule',
              icon: 'material-symbols:calendar-month-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson-schedule:calendar'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lessons',
            name: 'EducationAcademicLessonList',
            component: () => import('~/education/views/academic/LessonList.vue'),
            meta: {
              title: 'Lessons',
              icon: 'material-symbols:event-note-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/attendance-review',
            name: 'EducationAcademicAttendanceReview',
            component: () => import('~/education/views/academic/AttendanceReview.vue'),
            meta: {
              title: 'Attendance Review',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:academic:attendance:lesson-page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/leave-requests',
            name: 'EducationAcademicLeaveRequestList',
            component: () => import('~/education/views/academic/LeaveRequestList.vue'),
            meta: {
              title: 'Leave Requests',
              icon: 'material-symbols:event-busy-outline-rounded',
              type: 'M',
              auth: ['education:academic:leave-request:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lesson-changes',
            name: 'EducationAcademicLessonChangeList',
            component: () => import('~/education/views/academic/LessonChangeList.vue'),
            meta: {
              title: 'Lesson Changes',
              icon: 'material-symbols:move-up-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson-change:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/consumptions',
            name: 'EducationAcademicConsumptionLedgerList',
            component: () => import('~/education/views/academic/ConsumptionLedgerList.vue'),
            meta: {
              title: 'Consumption Ledger',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:academic:consumption:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/account-adjustments',
            name: 'EducationAcademicAccountAdjustmentList',
            component: () => import('~/education/views/academic/AccountAdjustmentList.vue'),
            meta: {
              title: 'Account Adjustments',
              icon: 'material-symbols:price-change-outline-rounded',
              type: 'M',
              auth: ['education:academic:account-adjustment:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/notices',
            name: 'EducationAcademicNoticeList',
            component: () => import('~/education/views/academic/NoticeList.vue'),
            meta: {
              title: 'Notices',
              icon: 'material-symbols:campaign-outline-rounded',
              type: 'M',
              auth: ['education:academic:notice:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/attendance',
            name: 'EducationAttendanceReport',
            component: () => import('~/education/views/academic/AttendanceReport.vue'),
            meta: {
              title: 'Attendance Report',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:attendance'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/consumption',
            name: 'EducationConsumptionReport',
            component: () => import('~/education/views/academic/ConsumptionReport.vue'),
            meta: {
              title: 'Consumption Report',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:consumption'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/account-balances',
            name: 'EducationAccountBalanceReport',
            component: () => import('~/education/views/academic/AccountBalanceReport.vue'),
            meta: {
              title: 'Account Balance Report',
              icon: 'material-symbols:account-balance-wallet-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:account-balance'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/leaves',
            name: 'EducationLeaveReport',
            component: () => import('~/education/views/academic/LeaveReport.vue'),
            meta: {
              title: 'Leave Report',
              icon: 'material-symbols:event-busy-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:leave'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/v1-acceptance',
            name: 'EducationV1AcceptanceReport',
            component: () => import('~/education/views/academic/V1AcceptanceReport.vue'),
            meta: {
              title: 'V1 Acceptance',
              icon: 'material-symbols:verified-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:acceptance'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/admissions',
        name: 'EducationAdmissions',
        redirect: '/education/admissions/leads',
        meta: {
          title: 'Admissions CRM',
          icon: 'material-symbols:hub-outline-rounded',
          type: 'M',
          auth: ['education:admissions:lead-source:page', 'education:admissions:lead:page', 'education:admissions:trial:page', 'education:admissions:lead:convert', 'education:admissions:task:page', 'education:admissions:dashboard:overview'],
        },
        children: [
          {
            path: '/education/admissions/lead-sources',
            name: 'EducationAdmissionLeadSourceList',
            component: () => import('~/education/views/admissions/LeadSourceList.vue'),
            meta: {
              title: 'Lead Sources',
              icon: 'material-symbols:source-environment-outline-rounded',
              type: 'M',
              auth: ['education:admissions:lead-source:page'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/leads',
            name: 'EducationAdmissionLeadPool',
            component: () => import('~/education/views/admissions/LeadPool.vue'),
            meta: {
              title: 'Lead Pool',
              icon: 'material-symbols:group-search-outline-rounded',
              type: 'M',
              auth: ['education:admissions:lead:page'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/leads/:id',
            name: 'EducationAdmissionLeadDetail',
            component: () => import('~/education/views/admissions/LeadDetail.vue'),
            meta: {
              title: 'Lead Detail',
              icon: 'material-symbols:contact-page-outline-rounded',
              type: 'M',
              auth: ['education:admissions:lead:detail'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/trials',
            name: 'EducationAdmissionTrialCalendar',
            component: () => import('~/education/views/admissions/TrialLessonCalendar.vue'),
            meta: {
              title: 'Trial Calendar',
              icon: 'material-symbols:event-available-outline-rounded',
              type: 'M',
              auth: ['education:admissions:trial:page'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/trial-feedbacks',
            name: 'EducationAdmissionTrialFeedbackList',
            component: () => import('~/education/views/admissions/TrialFeedbackList.vue'),
            meta: {
              title: 'Trial Feedback',
              icon: 'material-symbols:rate-review-outline-rounded',
              type: 'M',
              auth: ['education:admissions:trial-feedback:create'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/conversion',
            name: 'EducationAdmissionConversionWorkbench',
            component: () => import('~/education/views/admissions/LeadConversionWorkbench.vue'),
            meta: {
              title: 'Conversion',
              icon: 'material-symbols:published-with-changes-rounded',
              type: 'M',
              auth: ['education:admissions:lead:convert'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/tasks',
            name: 'EducationAdmissionTaskList',
            component: () => import('~/education/views/admissions/AdmissionTaskList.vue'),
            meta: {
              title: 'Admission Tasks',
              icon: 'material-symbols:task-alt-outline-rounded',
              type: 'M',
              auth: ['education:admissions:task:page'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/dashboard',
            name: 'EducationAdmissionDashboard',
            component: () => import('~/education/views/admissions/AdmissionDashboard.vue'),
            meta: {
              title: 'Admissions Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:admissions:dashboard:overview'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/operations',
        name: 'EducationOperations',
        redirect: '/education/operations/dashboard',
        meta: {
          title: 'Academic Operations',
          icon: 'material-symbols:monitoring-outline-rounded',
          type: 'M',
          auth: ['education:operations:lesson-change:page', 'education:operations:makeup:page', 'education:operations:consumption-review:page', 'education:operations:renewal-alert:page', 'education:operations:teacher-workload:report', 'education:operations:dashboard:overview'],
        },
        children: [
          {
            path: '/education/operations/lesson-changes',
            name: 'EducationOperationLessonChangeCenter',
            component: () => import('~/education/views/operations/LessonChangeCenter.vue'),
            meta: {
              title: 'Lesson Change Center',
              icon: 'material-symbols:move-up-outline-rounded',
              type: 'M',
              auth: ['education:operations:lesson-change:page'],
              cache: true,
            },
          },
          {
            path: '/education/operations/makeups',
            name: 'EducationOperationMakeupList',
            component: () => import('~/education/views/operations/LeaveMakeupList.vue'),
            meta: {
              title: 'Leave Make-up Closure',
              icon: 'material-symbols:event-available-outline-rounded',
              type: 'M',
              auth: ['education:operations:makeup:page'],
              cache: true,
            },
          },
          {
            path: '/education/operations/consumption-reviews',
            name: 'EducationOperationConsumptionReviewList',
            component: () => import('~/education/views/operations/ConsumptionReviewList.vue'),
            meta: {
              title: 'Consumption Review',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:operations:consumption-review:page'],
              cache: true,
            },
          },
          {
            path: '/education/operations/renewal-alerts',
            name: 'EducationOperationRenewalAlertList',
            component: () => import('~/education/views/operations/RenewalAlertList.vue'),
            meta: {
              title: 'Renewal Alerts',
              icon: 'material-symbols:notification-important-outline-rounded',
              type: 'M',
              auth: ['education:operations:renewal-alert:page'],
              cache: true,
            },
          },
          {
            path: '/education/operations/teacher-workloads',
            name: 'EducationOperationTeacherWorkloadReport',
            component: () => import('~/education/views/operations/TeacherWorkloadReport.vue'),
            meta: {
              title: 'Teacher Workloads',
              icon: 'material-symbols:bar-chart-outline-rounded',
              type: 'M',
              auth: ['education:operations:teacher-workload:report'],
              cache: true,
            },
          },
          {
            path: '/education/operations/dashboard',
            name: 'EducationOperationDashboard',
            component: () => import('~/education/views/operations/OperationDashboard.vue'),
            meta: {
              title: 'Operation Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:operations:dashboard:overview'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/finance',
        name: 'EducationFinance',
        redirect: '/education/finance/dashboard',
        meta: {
          title: 'Finance Payment',
          icon: 'material-symbols:payments-outline-rounded',
          type: 'M',
          auth: ['education:finance:order:page', 'education:finance:payment:page', 'education:finance:payment-channel:page', 'education:finance:refund:page', 'education:finance:receipt:page', 'education:finance:reconciliation:page', 'education:finance:dashboard:overview'],
        },
        children: [
          {
            path: '/education/finance/dashboard',
            name: 'EducationFinanceDashboard',
            component: () => import('~/education/views/finance/FinanceDashboard.vue'),
            meta: {
              title: 'Finance Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:finance:dashboard:overview'],
              cache: true,
            },
          },
          {
            path: '/education/finance/orders',
            name: 'EducationFinanceOrderList',
            component: () => import('~/education/views/finance/FinanceOrderList.vue'),
            meta: {
              title: 'Finance Orders',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:finance:order:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/payments',
            name: 'EducationFinancePaymentRecordList',
            component: () => import('~/education/views/finance/PaymentRecordList.vue'),
            meta: {
              title: 'Payment Records',
              icon: 'material-symbols:credit-card-outline-rounded',
              type: 'M',
              auth: ['education:finance:payment:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/channels',
            name: 'EducationFinancePaymentChannelList',
            component: () => import('~/education/views/finance/PaymentChannelList.vue'),
            meta: {
              title: 'Payment Channels',
              icon: 'material-symbols:settings-input-component-outline-rounded',
              type: 'M',
              auth: ['education:finance:payment-channel:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/refunds',
            name: 'EducationFinanceRefundRequestList',
            component: () => import('~/education/views/finance/RefundRequestList.vue'),
            meta: {
              title: 'Refund Requests',
              icon: 'material-symbols:assignment-return-outline-rounded',
              type: 'M',
              auth: ['education:finance:refund:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/receipts',
            name: 'EducationFinanceReceiptList',
            component: () => import('~/education/views/finance/ReceiptList.vue'),
            meta: {
              title: 'Receipts',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:finance:receipt:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/reconciliation',
            name: 'EducationFinanceReconciliationBatchList',
            component: () => import('~/education/views/finance/ReconciliationBatchList.vue'),
            meta: {
              title: 'Reconciliation',
              icon: 'material-symbols:compare-arrows-rounded',
              type: 'M',
              auth: ['education:finance:reconciliation:page'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/payroll',
        name: 'EducationPayroll',
        redirect: '/education/payroll/rules',
        meta: {
          title: 'Teacher Payroll',
          icon: 'material-symbols:account-balance-wallet-outline-rounded',
          type: 'M',
          auth: ['education:payroll:rule:page', 'education:payroll:batch:page', 'education:payroll:slip:page', 'education:payroll:review:page', 'education:payroll:payment:page', 'education:payroll:dispute:page', 'education:payroll:performance:page'],
        },
        children: [
          {
            path: '/education/payroll/rules',
            name: 'EducationPayrollSalaryRuleList',
            component: () => import('~/education/views/payroll/SalaryRuleList.vue'),
            meta: {
              title: 'Salary Rules',
              icon: 'material-symbols:rule-outline-rounded',
              type: 'M',
              auth: ['education:payroll:rule:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/batches',
            name: 'EducationPayrollSalaryBatchList',
            component: () => import('~/education/views/payroll/SalaryBatchList.vue'),
            meta: {
              title: 'Salary Batches',
              icon: 'material-symbols:calculate-outline-rounded',
              type: 'M',
              auth: ['education:payroll:batch:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/slips',
            name: 'EducationPayrollSalarySlipList',
            component: () => import('~/education/views/payroll/SalarySlipList.vue'),
            meta: {
              title: 'Salary Slips',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:payroll:slip:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/reviews',
            name: 'EducationPayrollSalaryReviewList',
            component: () => import('~/education/views/payroll/SalaryReviewList.vue'),
            meta: {
              title: 'Salary Reviews',
              icon: 'material-symbols:approval-outline-rounded',
              type: 'M',
              auth: ['education:payroll:review:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/payments',
            name: 'EducationPayrollSalaryPaymentList',
            component: () => import('~/education/views/payroll/SalaryPaymentList.vue'),
            meta: {
              title: 'Salary Payments',
              icon: 'material-symbols:payments-outline-rounded',
              type: 'M',
              auth: ['education:payroll:payment:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/disputes',
            name: 'EducationPayrollWorkloadDisputeList',
            component: () => import('~/education/views/payroll/WorkloadDisputeList.vue'),
            meta: {
              title: 'Workload Disputes',
              icon: 'material-symbols:gavel-outline-rounded',
              type: 'M',
              auth: ['education:payroll:dispute:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/performance',
            name: 'EducationPayrollTeacherPerformanceDashboard',
            component: () => import('~/education/views/payroll/TeacherPerformanceDashboard.vue'),
            meta: {
              title: 'Teacher Performance',
              icon: 'material-symbols:monitoring-outline-rounded',
              type: 'M',
              auth: ['education:payroll:performance:page'],
              cache: true,
            },
          },
        ],
      },
    ],
  },
]

export default educationRoutes
