import type { RouteRecordRaw } from 'vue-router'

const educationRoutes: RouteRecordRaw[] = [
  {
    path: '/education',
    name: 'EducationRoot',
    redirect: '/education/foundation/tenants',
    meta: {
      title: '教务 SaaS',
      icon: 'material-symbols:school-outline-rounded',
      type: 'M',
      auth: ['education:*'],
    },
    children: [
      {
        path: '/education/foundation',
        name: 'EducationFoundation',
        redirect: '/education/foundation/tenants',
        meta: {
          title: '基础设置',
          icon: 'material-symbols:settings-outline-rounded',
          type: 'M',
          auth: ['education:foundation:tenant:page', 'education:foundation:campus:page', 'education:foundation:user-profile:page', 'education:foundation:dictionary:page', 'education:foundation:feature-flag:page', 'education:foundation:audit-log:page'],
        },
        children: [
          {
            path: '/education/foundation/tenants',
            name: 'EducationFoundationTenantList',
            component: () => import('~/education/views/foundation/TenantList.vue'),
            meta: {
              title: '机构',
              icon: 'material-symbols:business-center-outline-rounded',
              type: 'M',
              auth: ['education:foundation:tenant:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/campuses',
            name: 'EducationFoundationCampusList',
            component: () => import('~/education/views/foundation/CampusList.vue'),
            meta: {
              title: '校区',
              icon: 'material-symbols:location-city-outline-rounded',
              type: 'M',
              auth: ['education:foundation:campus:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/user-profiles',
            name: 'EducationFoundationUserProfileList',
            component: () => import('~/education/views/foundation/UserProfileList.vue'),
            meta: {
              title: '人员权限',
              icon: 'material-symbols:manage-accounts-outline-rounded',
              type: 'M',
              auth: ['education:foundation:user-profile:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/dictionaries',
            name: 'EducationFoundationDictionaryList',
            component: () => import('~/education/views/foundation/DictionaryList.vue'),
            meta: {
              title: '字典配置',
              icon: 'material-symbols:format-list-bulleted-rounded',
              type: 'M',
              auth: ['education:foundation:dictionary:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/feature-flags',
            name: 'EducationFoundationFeatureFlagList',
            component: () => import('~/education/views/foundation/FeatureFlagList.vue'),
            meta: {
              title: '功能开关',
              icon: 'material-symbols:toggle-on-outline-rounded',
              type: 'M',
              auth: ['education:foundation:feature-flag:page'],
              cache: true,
            },
          },
          {
            path: '/education/foundation/audit-logs',
            name: 'EducationFoundationAuditLogList',
            component: () => import('~/education/views/foundation/AuditLogList.vue'),
            meta: {
              title: 'Audit Logs',
              icon: 'i-lucide-file-clock',
              type: 'M',
              auth: ['education:foundation:audit-log:page'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/academic',
        name: 'EducationAcademic',
        redirect: '/education/academic/dashboard',
        meta: {
          title: 'V1 Academic',
          icon: 'material-symbols:auto-stories-outline-rounded',
          type: 'M',
          auth: ['education:academic:report:dashboard', 'education:academic:report:attendance', 'education:academic:report:consumption', 'education:academic:report:account-balance', 'education:academic:report:leave', 'education:academic:report:acceptance', 'education:academic:classroom:page', 'education:academic:student:page', 'education:academic:guardian:page', 'education:academic:teacher:page', 'education:academic:course:page', 'education:academic:lesson-package:page', 'education:academic:enrollment:page', 'education:academic:student-course-account:page', 'education:academic:class:page', 'education:academic:lesson-schedule:calendar', 'education:academic:lesson:page', 'education:academic:attendance:lesson-page', 'education:academic:leave-request:page', 'education:academic:lesson-change:page', 'education:academic:consumption:page', 'education:academic:account-adjustment:page', 'education:academic:notice:page'],
        },
        children: [
          {
            path: '/education/academic/dashboard',
            name: 'EducationAcademicDashboard',
            component: () => import('~/education/views/academic/AcademicDashboard.vue'),
            meta: {
              title: 'Academic Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:dashboard'],
              cache: true,
            },
          },
          {
            path: '/education/academic/classrooms',
            name: 'EducationAcademicClassroomList',
            component: () => import('~/education/views/academic/ClassroomList.vue'),
            meta: {
              title: 'Classrooms',
              icon: 'material-symbols:meeting-room-outline-rounded',
              type: 'M',
              auth: ['education:academic:classroom:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/students',
            name: 'EducationAcademicStudentList',
            component: () => import('~/education/views/academic/StudentList.vue'),
            meta: {
              title: 'Students',
              icon: 'material-symbols:face-3-outline-rounded',
              type: 'M',
              auth: ['education:academic:student:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/guardians',
            name: 'EducationAcademicGuardianList',
            component: () => import('~/education/views/academic/GuardianList.vue'),
            meta: {
              title: 'Guardians',
              icon: 'material-symbols:family-restroom-rounded',
              type: 'M',
              auth: ['education:academic:guardian:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/teachers',
            name: 'EducationAcademicTeacherList',
            component: () => import('~/education/views/academic/TeacherList.vue'),
            meta: {
              title: 'Teachers',
              icon: 'material-symbols:co-present-outline-rounded',
              type: 'M',
              auth: ['education:academic:teacher:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/courses',
            name: 'EducationAcademicCourseList',
            component: () => import('~/education/views/academic/CourseList.vue'),
            meta: {
              title: 'Courses',
              icon: 'material-symbols:menu-book-outline-rounded',
              type: 'M',
              auth: ['education:academic:course:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lesson-packages',
            name: 'EducationAcademicLessonPackageList',
            component: () => import('~/education/views/academic/LessonPackageList.vue'),
            meta: {
              title: 'Lesson Packages',
              icon: 'material-symbols:inventory-2-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson-package:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/enrollments',
            name: 'EducationAcademicEnrollmentWorkbench',
            component: () => import('~/education/views/academic/EnrollmentWorkbench.vue'),
            meta: {
              title: 'Enrollments',
              icon: 'material-symbols:how-to-reg-outline-rounded',
              type: 'M',
              auth: ['education:academic:enrollment:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/course-accounts',
            name: 'EducationAcademicAccountLedgerList',
            component: () => import('~/education/views/academic/AccountLedgerList.vue'),
            meta: {
              title: 'Course Accounts',
              icon: 'material-symbols:account-balance-wallet-outline-rounded',
              type: 'M',
              auth: ['education:academic:student-course-account:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/classes',
            name: 'EducationAcademicClassList',
            component: () => import('~/education/views/academic/ClassList.vue'),
            meta: {
              title: 'Classes',
              icon: 'material-symbols:groups-outline-rounded',
              type: 'M',
              auth: ['education:academic:class:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lesson-schedule',
            name: 'EducationAcademicLessonScheduleCalendar',
            component: () => import('~/education/views/academic/LessonScheduleCalendar.vue'),
            meta: {
              title: 'Lesson Schedule',
              icon: 'material-symbols:calendar-month-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson-schedule:calendar'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lessons',
            name: 'EducationAcademicLessonList',
            component: () => import('~/education/views/academic/LessonList.vue'),
            meta: {
              title: 'Lessons',
              icon: 'material-symbols:event-note-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/attendance-review',
            name: 'EducationAcademicAttendanceReview',
            component: () => import('~/education/views/academic/AttendanceReview.vue'),
            meta: {
              title: 'Attendance Review',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:academic:attendance:lesson-page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/leave-requests',
            name: 'EducationAcademicLeaveRequestList',
            component: () => import('~/education/views/academic/LeaveRequestList.vue'),
            meta: {
              title: 'Leave Requests',
              icon: 'material-symbols:event-busy-outline-rounded',
              type: 'M',
              auth: ['education:academic:leave-request:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/lesson-changes',
            name: 'EducationAcademicLessonChangeList',
            component: () => import('~/education/views/academic/LessonChangeList.vue'),
            meta: {
              title: 'Lesson Changes',
              icon: 'material-symbols:move-up-outline-rounded',
              type: 'M',
              auth: ['education:academic:lesson-change:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/consumptions',
            name: 'EducationAcademicConsumptionLedgerList',
            component: () => import('~/education/views/academic/ConsumptionLedgerList.vue'),
            meta: {
              title: 'Consumption Ledger',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:academic:consumption:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/account-adjustments',
            name: 'EducationAcademicAccountAdjustmentList',
            component: () => import('~/education/views/academic/AccountAdjustmentList.vue'),
            meta: {
              title: 'Account Adjustments',
              icon: 'material-symbols:price-change-outline-rounded',
              type: 'M',
              auth: ['education:academic:account-adjustment:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/notices',
            name: 'EducationAcademicNoticeList',
            component: () => import('~/education/views/academic/NoticeList.vue'),
            meta: {
              title: 'Notices',
              icon: 'material-symbols:campaign-outline-rounded',
              type: 'M',
              auth: ['education:academic:notice:page'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/attendance',
            name: 'EducationAttendanceReport',
            component: () => import('~/education/views/academic/AttendanceReport.vue'),
            meta: {
              title: 'Attendance Report',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:attendance'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/consumption',
            name: 'EducationConsumptionReport',
            component: () => import('~/education/views/academic/ConsumptionReport.vue'),
            meta: {
              title: 'Consumption Report',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:consumption'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/account-balances',
            name: 'EducationAccountBalanceReport',
            component: () => import('~/education/views/academic/AccountBalanceReport.vue'),
            meta: {
              title: 'Account Balance Report',
              icon: 'material-symbols:account-balance-wallet-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:account-balance'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/leaves',
            name: 'EducationLeaveReport',
            component: () => import('~/education/views/academic/LeaveReport.vue'),
            meta: {
              title: 'Leave Report',
              icon: 'material-symbols:event-busy-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:leave'],
              cache: true,
            },
          },
          {
            path: '/education/academic/reports/v1-acceptance',
            name: 'EducationV1AcceptanceReport',
            component: () => import('~/education/views/academic/V1AcceptanceReport.vue'),
            meta: {
              title: 'V1 Acceptance',
              icon: 'material-symbols:verified-outline-rounded',
              type: 'M',
              auth: ['education:academic:report:acceptance'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/admissions',
        name: 'EducationAdmissions',
        redirect: '/education/admissions/leads',
        meta: {
          title: 'Admissions CRM',
          icon: 'material-symbols:hub-outline-rounded',
          type: 'M',
          auth: ['education:admissions:lead-source:page', 'education:admissions:lead:page', 'education:admissions:trial:page', 'education:admissions:lead:convert', 'education:admissions:task:page', 'education:admissions:dashboard:overview'],
        },
        children: [
          {
            path: '/education/admissions/lead-sources',
            name: 'EducationAdmissionLeadSourceList',
            component: () => import('~/education/views/admissions/LeadSourceList.vue'),
            meta: {
              title: 'Lead Sources',
              icon: 'material-symbols:source-environment-outline-rounded',
              type: 'M',
              auth: ['education:admissions:lead-source:page'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/leads',
            name: 'EducationAdmissionLeadPool',
            component: () => import('~/education/views/admissions/LeadPool.vue'),
            meta: {
              title: 'Lead Pool',
              icon: 'material-symbols:group-search-outline-rounded',
              type: 'M',
              auth: ['education:admissions:lead:page'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/leads/:id',
            name: 'EducationAdmissionLeadDetail',
            component: () => import('~/education/views/admissions/LeadDetail.vue'),
            meta: {
              title: 'Lead Detail',
              icon: 'material-symbols:contact-page-outline-rounded',
              type: 'M',
              auth: ['education:admissions:lead:detail'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/trials',
            name: 'EducationAdmissionTrialCalendar',
            component: () => import('~/education/views/admissions/TrialLessonCalendar.vue'),
            meta: {
              title: 'Trial Calendar',
              icon: 'material-symbols:event-available-outline-rounded',
              type: 'M',
              auth: ['education:admissions:trial:page'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/trial-feedbacks',
            name: 'EducationAdmissionTrialFeedbackList',
            component: () => import('~/education/views/admissions/TrialFeedbackList.vue'),
            meta: {
              title: 'Trial Feedback',
              icon: 'material-symbols:rate-review-outline-rounded',
              type: 'M',
              auth: ['education:admissions:trial-feedback:create'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/conversion',
            name: 'EducationAdmissionConversionWorkbench',
            component: () => import('~/education/views/admissions/LeadConversionWorkbench.vue'),
            meta: {
              title: 'Conversion',
              icon: 'material-symbols:published-with-changes-rounded',
              type: 'M',
              auth: ['education:admissions:lead:convert'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/tasks',
            name: 'EducationAdmissionTaskList',
            component: () => import('~/education/views/admissions/AdmissionTaskList.vue'),
            meta: {
              title: 'Admission Tasks',
              icon: 'material-symbols:task-alt-outline-rounded',
              type: 'M',
              auth: ['education:admissions:task:page'],
              cache: true,
            },
          },
          {
            path: '/education/admissions/dashboard',
            name: 'EducationAdmissionDashboard',
            component: () => import('~/education/views/admissions/AdmissionDashboard.vue'),
            meta: {
              title: 'Admissions Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:admissions:dashboard:overview'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/operations',
        name: 'EducationOperations',
        redirect: '/education/operations/dashboard',
        meta: {
          title: 'Academic Operations',
          icon: 'material-symbols:monitoring-outline-rounded',
          type: 'M',
          auth: ['education:operations:lesson-change:page', 'education:operations:makeup:page', 'education:operations:consumption-review:page', 'education:operations:renewal-alert:page', 'education:operations:teacher-workload:report', 'education:operations:dashboard:overview'],
        },
        children: [
          {
            path: '/education/operations/lesson-changes',
            name: 'EducationOperationLessonChangeCenter',
            component: () => import('~/education/views/operations/LessonChangeCenter.vue'),
            meta: {
              title: 'Lesson Change Center',
              icon: 'material-symbols:move-up-outline-rounded',
              type: 'M',
              auth: ['education:operations:lesson-change:page'],
              cache: true,
            },
          },
          {
            path: '/education/operations/makeups',
            name: 'EducationOperationMakeupList',
            component: () => import('~/education/views/operations/LeaveMakeupList.vue'),
            meta: {
              title: 'Leave Make-up Closure',
              icon: 'material-symbols:event-available-outline-rounded',
              type: 'M',
              auth: ['education:operations:makeup:page'],
              cache: true,
            },
          },
          {
            path: '/education/operations/consumption-reviews',
            name: 'EducationOperationConsumptionReviewList',
            component: () => import('~/education/views/operations/ConsumptionReviewList.vue'),
            meta: {
              title: 'Consumption Review',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:operations:consumption-review:page'],
              cache: true,
            },
          },
          {
            path: '/education/operations/renewal-alerts',
            name: 'EducationOperationRenewalAlertList',
            component: () => import('~/education/views/operations/RenewalAlertList.vue'),
            meta: {
              title: 'Renewal Alerts',
              icon: 'material-symbols:notification-important-outline-rounded',
              type: 'M',
              auth: ['education:operations:renewal-alert:page'],
              cache: true,
            },
          },
          {
            path: '/education/operations/teacher-workloads',
            name: 'EducationOperationTeacherWorkloadReport',
            component: () => import('~/education/views/operations/TeacherWorkloadReport.vue'),
            meta: {
              title: 'Teacher Workloads',
              icon: 'material-symbols:bar-chart-outline-rounded',
              type: 'M',
              auth: ['education:operations:teacher-workload:report'],
              cache: true,
            },
          },
          {
            path: '/education/operations/dashboard',
            name: 'EducationOperationDashboard',
            component: () => import('~/education/views/operations/OperationDashboard.vue'),
            meta: {
              title: 'Operation Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:operations:dashboard:overview'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/finance',
        name: 'EducationFinance',
        redirect: '/education/finance/dashboard',
        meta: {
          title: 'Finance Payment',
          icon: 'material-symbols:payments-outline-rounded',
          type: 'M',
          auth: ['education:finance:order:page', 'education:finance:payment:page', 'education:finance:payment-channel:page', 'education:finance:refund:page', 'education:finance:receipt:page', 'education:finance:reconciliation:page', 'education:finance:dashboard:overview'],
        },
        children: [
          {
            path: '/education/finance/dashboard',
            name: 'EducationFinanceDashboard',
            component: () => import('~/education/views/finance/FinanceDashboard.vue'),
            meta: {
              title: 'Finance Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:finance:dashboard:overview'],
              cache: true,
            },
          },
          {
            path: '/education/finance/orders',
            name: 'EducationFinanceOrderList',
            component: () => import('~/education/views/finance/FinanceOrderList.vue'),
            meta: {
              title: 'Finance Orders',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:finance:order:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/payments',
            name: 'EducationFinancePaymentRecordList',
            component: () => import('~/education/views/finance/PaymentRecordList.vue'),
            meta: {
              title: 'Payment Records',
              icon: 'material-symbols:credit-card-outline-rounded',
              type: 'M',
              auth: ['education:finance:payment:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/channels',
            name: 'EducationFinancePaymentChannelList',
            component: () => import('~/education/views/finance/PaymentChannelList.vue'),
            meta: {
              title: 'Payment Channels',
              icon: 'material-symbols:settings-input-component-outline-rounded',
              type: 'M',
              auth: ['education:finance:payment-channel:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/refunds',
            name: 'EducationFinanceRefundRequestList',
            component: () => import('~/education/views/finance/RefundRequestList.vue'),
            meta: {
              title: 'Refund Requests',
              icon: 'material-symbols:assignment-return-outline-rounded',
              type: 'M',
              auth: ['education:finance:refund:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/receipts',
            name: 'EducationFinanceReceiptList',
            component: () => import('~/education/views/finance/ReceiptList.vue'),
            meta: {
              title: 'Receipts',
              icon: 'material-symbols:fact-check-outline-rounded',
              type: 'M',
              auth: ['education:finance:receipt:page'],
              cache: true,
            },
          },
          {
            path: '/education/finance/reconciliation',
            name: 'EducationFinanceReconciliationBatchList',
            component: () => import('~/education/views/finance/ReconciliationBatchList.vue'),
            meta: {
              title: 'Reconciliation',
              icon: 'material-symbols:compare-arrows-rounded',
              type: 'M',
              auth: ['education:finance:reconciliation:page'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/payroll',
        name: 'EducationPayroll',
        redirect: '/education/payroll/rules',
        meta: {
          title: 'Teacher Payroll',
          icon: 'material-symbols:account-balance-wallet-outline-rounded',
          type: 'M',
          auth: ['education:payroll:rule:page', 'education:payroll:batch:page', 'education:payroll:slip:page', 'education:payroll:review:page', 'education:payroll:payment:page', 'education:payroll:dispute:page', 'education:payroll:performance:page'],
        },
        children: [
          {
            path: '/education/payroll/rules',
            name: 'EducationPayrollSalaryRuleList',
            component: () => import('~/education/views/payroll/SalaryRuleList.vue'),
            meta: {
              title: 'Salary Rules',
              icon: 'material-symbols:rule-outline-rounded',
              type: 'M',
              auth: ['education:payroll:rule:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/batches',
            name: 'EducationPayrollSalaryBatchList',
            component: () => import('~/education/views/payroll/SalaryBatchList.vue'),
            meta: {
              title: 'Salary Batches',
              icon: 'material-symbols:calculate-outline-rounded',
              type: 'M',
              auth: ['education:payroll:batch:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/slips',
            name: 'EducationPayrollSalarySlipList',
            component: () => import('~/education/views/payroll/SalarySlipList.vue'),
            meta: {
              title: 'Salary Slips',
              icon: 'material-symbols:receipt-long-outline-rounded',
              type: 'M',
              auth: ['education:payroll:slip:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/reviews',
            name: 'EducationPayrollSalaryReviewList',
            component: () => import('~/education/views/payroll/SalaryReviewList.vue'),
            meta: {
              title: 'Salary Reviews',
              icon: 'material-symbols:approval-outline-rounded',
              type: 'M',
              auth: ['education:payroll:review:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/payments',
            name: 'EducationPayrollSalaryPaymentList',
            component: () => import('~/education/views/payroll/SalaryPaymentList.vue'),
            meta: {
              title: 'Salary Payments',
              icon: 'material-symbols:payments-outline-rounded',
              type: 'M',
              auth: ['education:payroll:payment:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/disputes',
            name: 'EducationPayrollWorkloadDisputeList',
            component: () => import('~/education/views/payroll/WorkloadDisputeList.vue'),
            meta: {
              title: 'Workload Disputes',
              icon: 'material-symbols:gavel-outline-rounded',
              type: 'M',
              auth: ['education:payroll:dispute:page'],
              cache: true,
            },
          },
          {
            path: '/education/payroll/performance',
            name: 'EducationPayrollTeacherPerformanceDashboard',
            component: () => import('~/education/views/payroll/TeacherPerformanceDashboard.vue'),
            meta: {
              title: 'Teacher Performance',
              icon: 'material-symbols:monitoring-outline-rounded',
              type: 'M',
              auth: ['education:payroll:performance:page'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/family',
        name: 'EducationFamily',
        redirect: '/education/family/homework',
        meta: {
          title: 'Family Service',
          icon: 'material-symbols:family-restroom-rounded',
          type: 'M',
          auth: ['education:family:comment-template:page', 'education:family:performance-tag:page', 'education:family:homework:page', 'education:family:report:page', 'education:family:growth:page', 'education:family:message:page', 'education:family:quality:page'],
        },
        children: [
          {
            path: '/education/family/comment-templates',
            name: 'EducationFamilyCommentTemplateList',
            component: () => import('~/education/views/family/CommentTemplateList.vue'),
            meta: {
              title: 'Comment Templates',
              icon: 'material-symbols:rate-review-outline-rounded',
              type: 'M',
              auth: ['education:family:comment-template:page'],
              cache: true,
            },
          },
          {
            path: '/education/family/performance-tags',
            name: 'EducationFamilyPerformanceTagList',
            component: () => import('~/education/views/family/PerformanceTagList.vue'),
            meta: {
              title: 'Performance Tags',
              icon: 'material-symbols:label-outline-rounded',
              type: 'M',
              auth: ['education:family:performance-tag:page'],
              cache: true,
            },
          },
          {
            path: '/education/family/homework',
            name: 'EducationFamilyHomeworkAssignmentList',
            component: () => import('~/education/views/family/HomeworkAssignmentList.vue'),
            meta: {
              title: 'Homework',
              icon: 'material-symbols:assignment-outline-rounded',
              type: 'M',
              auth: ['education:family:homework:page'],
              cache: true,
            },
          },
          {
            path: '/education/family/reports',
            name: 'EducationFamilyLearningReportList',
            component: () => import('~/education/views/family/LearningReportList.vue'),
            meta: {
              title: 'Learning Reports',
              icon: 'material-symbols:summarize-outline-rounded',
              type: 'M',
              auth: ['education:family:report:page'],
              cache: true,
            },
          },
          {
            path: '/education/family/growth-records',
            name: 'EducationFamilyGrowthRecordList',
            component: () => import('~/education/views/family/GrowthRecordList.vue'),
            meta: {
              title: 'Growth Records',
              icon: 'material-symbols:trending-up-rounded',
              type: 'M',
              auth: ['education:family:growth:page'],
              cache: true,
            },
          },
          {
            path: '/education/family/messages',
            name: 'EducationFamilyMessageMonitor',
            component: () => import('~/education/views/family/FamilyMessageMonitor.vue'),
            meta: {
              title: 'Family Messages',
              icon: 'material-symbols:forum-outline-rounded',
              type: 'M',
              auth: ['education:family:message:page'],
              cache: true,
            },
          },
          {
            path: '/education/family/quality',
            name: 'EducationFamilyServiceQualityDashboard',
            component: () => import('~/education/views/family/ServiceQualityDashboard.vue'),
            meta: {
              title: 'Service Quality',
              icon: 'material-symbols:monitoring-outline-rounded',
              type: 'M',
              auth: ['education:family:quality:page'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/ai',
        name: 'EducationAi',
        redirect: '/education/ai/model-configs',
        meta: {
          title: 'AI Assistant',
          icon: 'material-symbols:psychology-outline-rounded',
          type: 'M',
          auth: ['education:ai:model-config:page', 'education:ai:prompt:page', 'education:ai:generation:page', 'education:ai:review:page', 'education:ai:risk-score:page', 'education:ai:data-question:create', 'education:ai:recommendation:page', 'education:ai:usage:summary', 'education:ai:safety:page'],
        },
        children: [
          {
            path: '/education/ai/model-configs',
            name: 'EducationAiModelConfigList',
            component: () => import('~/education/views/ai/AiModelConfigList.vue'),
            meta: {
              title: 'Model Configs',
              icon: 'material-symbols:tune-outline-rounded',
              type: 'M',
              auth: ['education:ai:model-config:page'],
              cache: true,
            },
          },
          {
            path: '/education/ai/prompts',
            name: 'EducationAiPromptTemplateList',
            component: () => import('~/education/views/ai/PromptTemplateList.vue'),
            meta: {
              title: 'Prompts',
              icon: 'material-symbols:prompt-suggestion-outline-rounded',
              type: 'M',
              auth: ['education:ai:prompt:page'],
              cache: true,
            },
          },
          {
            path: '/education/ai/generation-tasks',
            name: 'EducationAiGenerationTaskList',
            component: () => import('~/education/views/ai/GenerationTaskList.vue'),
            meta: {
              title: 'Generation Tasks',
              icon: 'material-symbols:queue-play-next-outline-rounded',
              type: 'M',
              auth: ['education:ai:generation:page'],
              cache: true,
            },
          },
          {
            path: '/education/ai/reviews',
            name: 'EducationAiReviewList',
            component: () => import('~/education/views/ai/AiReviewList.vue'),
            meta: {
              title: 'Reviews',
              icon: 'material-symbols:rate-review-outline-rounded',
              type: 'M',
              auth: ['education:ai:review:page'],
              cache: true,
            },
          },
          {
            path: '/education/ai/risk-scores',
            name: 'EducationAiRiskScoreList',
            component: () => import('~/education/views/ai/RiskScoreList.vue'),
            meta: {
              title: 'Risk Scores',
              icon: 'material-symbols:warning-outline-rounded',
              type: 'M',
              auth: ['education:ai:risk-score:page'],
              cache: true,
            },
          },
          {
            path: '/education/ai/data-questions',
            name: 'EducationAiDataQuestionWorkbench',
            component: () => import('~/education/views/ai/DataQuestionWorkbench.vue'),
            meta: {
              title: 'Data Q&A',
              icon: 'material-symbols:query-stats-outline-rounded',
              type: 'M',
              auth: ['education:ai:data-question:create'],
              cache: true,
            },
          },
          {
            path: '/education/ai/recommendations',
            name: 'EducationAiRecommendationList',
            component: () => import('~/education/views/ai/AiRecommendationList.vue'),
            meta: {
              title: 'Recommendations',
              icon: 'material-symbols:tips-and-updates-outline-rounded',
              type: 'M',
              auth: ['education:ai:recommendation:page'],
              cache: true,
            },
          },
          {
            path: '/education/ai/usage',
            name: 'EducationAiUsageDashboard',
            component: () => import('~/education/views/ai/UsageDashboard.vue'),
            meta: {
              title: 'Usage',
              icon: 'material-symbols:monitoring-outline-rounded',
              type: 'M',
              auth: ['education:ai:usage:summary'],
              cache: true,
            },
          },
          {
            path: '/education/ai/safety-events',
            name: 'EducationAiSafetyEventList',
            component: () => import('~/education/views/ai/SafetyEventList.vue'),
            meta: {
              title: 'Safety Events',
              icon: 'material-symbols:shield-outline-rounded',
              type: 'M',
              auth: ['education:ai:safety:page'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/workflow',
        name: 'EducationWorkflow',
        redirect: '/education/workflow/rules',
        meta: {
          title: 'Workflow',
          icon: 'material-symbols:account-tree-outline-rounded',
          type: 'M',
          auth: ['education:workflow:rule:page', 'education:workflow:task:page', 'education:workflow:alert:page', 'education:workflow:sla:page', 'education:workflow:escalation:page', 'education:workflow:template:page', 'education:workflow:metric:page'],
        },
        children: [
          {
            path: '/education/workflow/rules',
            name: 'EducationWorkflowRuleList',
            component: () => import('~/education/views/workflow/WorkflowRuleList.vue'),
            meta: {
              title: 'Rules',
              icon: 'material-symbols:rule-folder-outline-rounded',
              type: 'M',
              auth: ['education:workflow:rule:page'],
              cache: true,
            },
          },
          {
            path: '/education/workflow/tasks',
            name: 'EducationWorkflowTaskWorkbench',
            component: () => import('~/education/views/workflow/WorkflowTaskWorkbench.vue'),
            meta: {
              title: 'Tasks',
              icon: 'material-symbols:task-alt-outline-rounded',
              type: 'M',
              auth: ['education:workflow:task:page'],
              cache: true,
            },
          },
          {
            path: '/education/workflow/alerts',
            name: 'EducationWorkflowOperationAlertList',
            component: () => import('~/education/views/workflow/OperationAlertList.vue'),
            meta: {
              title: 'Alerts',
              icon: 'material-symbols:notification-important-outline-rounded',
              type: 'M',
              auth: ['education:workflow:alert:page'],
              cache: true,
            },
          },
          {
            path: '/education/workflow/sla-policies',
            name: 'EducationWorkflowSlaPolicyList',
            component: () => import('~/education/views/workflow/SlaPolicyList.vue'),
            meta: {
              title: 'SLA Policies',
              icon: 'material-symbols:timer-outline-rounded',
              type: 'M',
              auth: ['education:workflow:sla:page'],
              cache: true,
            },
          },
          {
            path: '/education/workflow/escalation-policies',
            name: 'EducationWorkflowEscalationPolicyList',
            component: () => import('~/education/views/workflow/EscalationPolicyList.vue'),
            meta: {
              title: 'Escalation',
              icon: 'material-symbols:upgrade-outline-rounded',
              type: 'M',
              auth: ['education:workflow:escalation:page'],
              cache: true,
            },
          },
          {
            path: '/education/workflow/templates',
            name: 'EducationWorkflowTemplateList',
            component: () => import('~/education/views/workflow/WorkflowTemplateList.vue'),
            meta: {
              title: 'Templates',
              icon: 'material-symbols:article-outline-rounded',
              type: 'M',
              auth: ['education:workflow:template:page'],
              cache: true,
            },
          },
          {
            path: '/education/workflow/metrics',
            name: 'EducationWorkflowMetricDashboard',
            component: () => import('~/education/views/workflow/WorkflowMetricDashboard.vue'),
            meta: {
              title: 'Metrics',
              icon: 'material-symbols:monitoring-outline-rounded',
              type: 'M',
              auth: ['education:workflow:metric:page'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/growth',
        name: 'EducationGrowth',
        redirect: '/education/growth/workbench',
        meta: {
          title: 'Growth',
          icon: 'material-symbols:trending-up-rounded',
          type: 'M',
          auth: ['education:growth:workbench:view', 'education:growth:score:recalculate', 'education:growth:ai-script:generate', 'education:growth:strategy:save', 'education:growth:trial-conversion:view', 'education:growth:channel-roi:page', 'education:growth:consultant-metric:page', 'education:growth:loss:create'],
        },
        children: [
          {
            path: '/education/growth/workbench',
            name: 'EducationGrowthWorkbench',
            component: () => import('~/education/views/growth/GrowthWorkbench.vue'),
            meta: {
              title: 'Workbench',
              icon: 'material-symbols:dashboard-customize-outline-rounded',
              type: 'M',
              auth: ['education:growth:workbench:view'],
              cache: true,
            },
          },
          {
            path: '/education/growth/lead-scores',
            name: 'EducationGrowthLeadScoreList',
            component: () => import('~/education/views/growth/LeadScoreList.vue'),
            meta: {
              title: 'Lead Scores',
              icon: 'material-symbols:scoreboard-outline-rounded',
              type: 'M',
              auth: ['education:growth:score:recalculate'],
              cache: true,
            },
          },
          {
            path: '/education/growth/ai-talk-scripts',
            name: 'EducationGrowthAiTalkScriptWorkbench',
            component: () => import('~/education/views/growth/AiTalkScriptWorkbench.vue'),
            meta: {
              title: 'AI Scripts',
              icon: 'material-symbols:smart-toy-outline-rounded',
              type: 'M',
              auth: ['education:growth:ai-script:generate'],
              cache: true,
            },
          },
          {
            path: '/education/growth/followup-strategies',
            name: 'EducationGrowthFollowupStrategyList',
            component: () => import('~/education/views/growth/FollowupStrategyList.vue'),
            meta: {
              title: 'Strategies',
              icon: 'material-symbols:low-priority-outline-rounded',
              type: 'M',
              auth: ['education:growth:strategy:save'],
              cache: true,
            },
          },
          {
            path: '/education/growth/trial-conversions',
            name: 'EducationGrowthTrialConversionList',
            component: () => import('~/education/views/growth/TrialConversionList.vue'),
            meta: {
              title: 'Trial Conversion',
              icon: 'material-symbols:published-with-changes-rounded',
              type: 'M',
              auth: ['education:growth:trial-conversion:view'],
              cache: true,
            },
          },
          {
            path: '/education/growth/channel-roi',
            name: 'EducationGrowthChannelRoiDashboard',
            component: () => import('~/education/views/growth/ChannelRoiDashboard.vue'),
            meta: {
              title: 'Channel ROI',
              icon: 'material-symbols:query-stats-rounded',
              type: 'M',
              auth: ['education:growth:channel-roi:page'],
              cache: true,
            },
          },
          {
            path: '/education/growth/consultant-metrics',
            name: 'EducationGrowthConsultantMetricDashboard',
            component: () => import('~/education/views/growth/ConsultantMetricDashboard.vue'),
            meta: {
              title: 'Consultant Metrics',
              icon: 'material-symbols:groups-2-outline-rounded',
              type: 'M',
              auth: ['education:growth:consultant-metric:page'],
              cache: true,
            },
          },
          {
            path: '/education/growth/loss-reasons',
            name: 'EducationGrowthLossReasonReport',
            component: () => import('~/education/views/growth/LossReasonReport.vue'),
            meta: {
              title: 'Loss Reasons',
              icon: 'material-symbols:playlist-remove-rounded',
              type: 'M',
              auth: ['education:growth:loss:create'],
              cache: true,
            },
          },
        ],
      },
      {
        path: '/education/standards',
        name: 'EducationStandards',
        redirect: '/education/standards/packages',
        meta: {
          title: 'Standards',
          icon: 'material-symbols:rule-settings-outline-rounded',
          type: 'M',
          auth: ['education:standards:package:page', 'education:standards:stage-goal:page', 'education:standards:ability:page', 'education:standards:trial:page', 'education:standards:delivery:page', 'education:standards:template:page', 'education:standards:material:page', 'education:standards:quality:page', 'education:standards:version:page'],
        },
        children: [
          {
            path: '/education/standards/packages',
            name: 'EducationStandardsServicePackageList',
            component: () => import('~/education/views/standards/ServicePackageList.vue'),
            meta: { title: 'Packages', icon: 'material-symbols:inventory-2-outline-rounded', type: 'M', auth: ['education:standards:package:page'], cache: true },
          },
          {
            path: '/education/standards/stage-goals',
            name: 'EducationStandardsStageGoalEditor',
            component: () => import('~/education/views/standards/StageGoalEditor.vue'),
            meta: { title: 'Stage Goals', icon: 'material-symbols:flag-outline-rounded', type: 'M', auth: ['education:standards:stage-goal:page'], cache: true },
          },
          {
            path: '/education/standards/ability-points',
            name: 'EducationStandardsAbilityPointList',
            component: () => import('~/education/views/standards/AbilityPointList.vue'),
            meta: { title: 'Ability Points', icon: 'material-symbols:psychology-outline-rounded', type: 'M', auth: ['education:standards:ability:page'], cache: true },
          },
          {
            path: '/education/standards/trial',
            name: 'EducationStandardsTrialStandardEditor',
            component: () => import('~/education/views/standards/TrialStandardEditor.vue'),
            meta: { title: 'Trial Standards', icon: 'material-symbols:science-outline-rounded', type: 'M', auth: ['education:standards:trial:page'], cache: true },
          },
          {
            path: '/education/standards/delivery',
            name: 'EducationStandardsDeliveryStandardEditor',
            component: () => import('~/education/views/standards/DeliveryStandardEditor.vue'),
            meta: { title: 'Delivery Standards', icon: 'material-symbols:fact-check-outline-rounded', type: 'M', auth: ['education:standards:delivery:page'], cache: true },
          },
          {
            path: '/education/standards/templates',
            name: 'EducationStandardsServiceTemplateList',
            component: () => import('~/education/views/standards/ServiceTemplateList.vue'),
            meta: { title: 'Templates', icon: 'material-symbols:dynamic-form-outline-rounded', type: 'M', auth: ['education:standards:template:page'], cache: true },
          },
          {
            path: '/education/standards/materials',
            name: 'EducationStandardsCourseMaterialList',
            component: () => import('~/education/views/standards/CourseMaterialList.vue'),
            meta: { title: 'Materials', icon: 'material-symbols:folder-open-outline-rounded', type: 'M', auth: ['education:standards:material:page'], cache: true },
          },
          {
            path: '/education/standards/feedback',
            name: 'EducationStandardsCourseFeedbackList',
            component: () => import('~/education/views/standards/CourseFeedbackList.vue'),
            meta: { title: 'Feedback', icon: 'material-symbols:rate-review-outline-rounded', type: 'M', auth: ['education:standards:quality:page'], cache: true },
          },
          {
            path: '/education/standards/quality',
            name: 'EducationStandardsCourseQualityDashboard',
            component: () => import('~/education/views/standards/CourseQualityDashboard.vue'),
            meta: { title: 'Quality', icon: 'material-symbols:monitoring-outline-rounded', type: 'M', auth: ['education:standards:quality:page'], cache: true },
          },
          {
            path: '/education/standards/versions',
            name: 'EducationStandardsStandardVersionList',
            component: () => import('~/education/views/standards/StandardVersionList.vue'),
            meta: { title: 'Versions', icon: 'material-symbols:published-with-changes-rounded', type: 'M', auth: ['education:standards:version:page'], cache: true },
          },
          {
            path: '/education/standards/reviews',
            name: 'EducationStandardsStandardReviewList',
            component: () => import('~/education/views/standards/StandardReviewList.vue'),
            meta: { title: 'Reviews', icon: 'material-symbols:approval-delegation-outline-rounded', type: 'M', auth: ['education:standards:review:page'], cache: true },
          },
        ],
      },
      {
        path: '/education/group',
        name: 'EducationGroup',
        redirect: '/education/group/dashboard',
        meta: {
          title: 'Group Governance',
          icon: 'material-symbols:account-tree-outline-rounded',
          type: 'M',
          auth: ['education:group:org:tree', 'education:group:data-permission:page', 'education:group:approval-template:page', 'education:group:approval-task:page', 'education:group:contract:page', 'education:group:contract-renewal:page', 'education:group:metric:page', 'education:group:franchise:page', 'education:group:risk-audit:page'],
        },
        children: [
          {
            path: '/education/group/dashboard',
            name: 'EducationGroupOperationDashboard',
            component: () => import('~/education/views/group/GroupOperationDashboard.vue'),
            meta: {
              title: 'Group Dashboard',
              icon: 'material-symbols:dashboard-outline-rounded',
              type: 'M',
              auth: ['education:group:metric:page'],
              cache: true,
            },
          },
          {
            path: '/education/group/org-units',
            name: 'EducationGroupOrgUnitTree',
            component: () => import('~/education/views/group/OrgUnitTree.vue'),
            meta: {
              title: 'Org Units',
              icon: 'material-symbols:account-tree-outline-rounded',
              type: 'M',
              auth: ['education:group:org:tree'],
              cache: true,
            },
          },
          {
            path: '/education/group/data-permissions',
            name: 'EducationGroupDataPermissionList',
            component: () => import('~/education/views/group/DataPermissionList.vue'),
            meta: {
              title: 'Data Permissions',
              icon: 'material-symbols:admin-panel-settings-outline-rounded',
              type: 'M',
              auth: ['education:group:data-permission:page'],
              cache: true,
            },
          },
          {
            path: '/education/group/approval-templates',
            name: 'EducationGroupApprovalTemplateList',
            component: () => import('~/education/views/group/ApprovalTemplateList.vue'),
            meta: {
              title: 'Approval Templates',
              icon: 'material-symbols:approval-outline-rounded',
              type: 'M',
              auth: ['education:group:approval-template:page'],
              cache: true,
            },
          },
          {
            path: '/education/group/approval-tasks',
            name: 'EducationGroupApprovalTaskList',
            component: () => import('~/education/views/group/ApprovalTaskList.vue'),
            meta: {
              title: 'Approval Tasks',
              icon: 'material-symbols:task-alt-outline-rounded',
              type: 'M',
              auth: ['education:group:approval-task:page'],
              cache: true,
            },
          },
          {
            path: '/education/group/contracts',
            name: 'EducationGroupContractList',
            component: () => import('~/education/views/group/ContractList.vue'),
            meta: {
              title: 'Contracts',
              icon: 'material-symbols:contract-outline-rounded',
              type: 'M',
              auth: ['education:group:contract:page'],
              cache: true,
            },
          },
          {
            path: '/education/group/contract-renewals',
            name: 'EducationGroupContractRenewalList',
            component: () => import('~/education/views/group/ContractRenewalList.vue'),
            meta: {
              title: 'Contract Renewals',
              icon: 'material-symbols:event-repeat-outline-rounded',
              type: 'M',
              auth: ['education:group:contract-renewal:page'],
              cache: true,
            },
          },
          {
            path: '/education/group/franchises',
            name: 'EducationGroupFranchiseRecordList',
            component: () => import('~/education/views/group/FranchiseRecordList.vue'),
            meta: {
              title: 'Franchises',
              icon: 'material-symbols:storefront-outline-rounded',
              type: 'M',
              auth: ['education:group:franchise:page'],
              cache: true,
            },
          },
          {
            path: '/education/group/risk-audits',
            name: 'EducationGroupRiskAuditEventList',
            component: () => import('~/education/views/group/RiskAuditEventList.vue'),
            meta: {
              title: 'Risk Audits',
              icon: 'material-symbols:warning-outline-rounded',
              type: 'M',
              auth: ['education:group:risk-audit:page'],
              cache: true,
            },
          },
        ],
      },
    ],
  },
]

export default educationRoutes
